import { StyleSheet, Platform } from 'react-native';

export const createPlexoBraquialStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    content: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      gap: 12,
    },
    title: {
      fontSize: 24,
      fontWeight: 'bold',
      color: colors.text,
      marginBottom: 8,
      textAlign: 'center',
      lineHeight: 30,
    },
    progressContainer: {
      alignItems: 'center',
      marginBottom: 20,
    },
    progressBar: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 8,
    },
    progressStep: {
      width: 40,
      height: 4,
      backgroundColor: colors.border,
      borderRadius: 2,
    },
    progressStepActive: {
      backgroundColor: colors.primary,
    },
    progressStepComplete: {
      backgroundColor: colors.success,
    },
    progressText: {
      fontSize: 14,
      color: colors.mutedText,
    },
    stepContainer: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    stepHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 12,
    },
    stepTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: colors.text,
      flex: 1,
    },
    stepDescription: {
      fontSize: 14,
      color: colors.mutedText,
      marginBottom: 16,
      lineHeight: 20,
    },
    muscleList: {
      maxHeight: 400,
    },
    muscleItem: {
      marginBottom: 16,
    },
    muscleLabel: {
      fontSize: 15,
      fontWeight: '500',
      color: colors.text,
      marginBottom: 8,
    },
    pickerContainer: {
      backgroundColor: colors.inputBackground,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 8,
      justifyContent: 'center',
      minHeight: 48,
      paddingHorizontal: Platform.OS === 'ios' ? 0 : 8,
    },
    picker: {
      color: colors.text,
      height: Platform.OS === 'ios' ? 48 : 48,
      fontSize: 14,
    },
    pickerItem: {
      fontSize: 14,
      height: 48,
      color: colors.text,
    },
    checkboxGroup: {
      gap: 12,
    },
    checkboxGroupTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 8,
    },
    checkboxItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 12,
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    checkboxItemSelected: {
      backgroundColor: colors.primaryLight,
      borderColor: colors.primary,
    },
    checkbox: {
      width: 20,
      height: 20,
      borderRadius: 4,
      borderWidth: 2,
      borderColor: colors.border,
      marginRight: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    checkboxChecked: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    checkboxCheck: {
      color: colors.buttonPrimaryText,
      fontSize: 12,
      fontWeight: 'bold',
    },
    checkboxLabel: {
      fontSize: 14,
      color: colors.text,
      flex: 1,
    },
    checkboxLabelSelected: {
      color: colors.primary,
      fontWeight: '500',
    },
    reflexContainer: {
      gap: 16,
    },
    reflexLabel: {
      fontSize: 15,
      fontWeight: '500',
      color: colors.text,
      marginBottom: 8,
    },
    additionalInfo: {
      gap: 16,
    },
    infoLabel: {
      fontSize: 15,
      fontWeight: '500',
      color: colors.text,
      marginBottom: 8,
    },
    navigationContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 20,
      gap: 16,
    },
    navButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.primary,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      flex: 1,
      justifyContent: 'center',
    },
    navButtonDisabled: {
      backgroundColor: colors.mutedBackground,
    },
    navButtonText: {
      color: colors.buttonPrimaryText,
      fontSize: 16,
      fontWeight: '600',
    },
    navButtonTextDisabled: {
      color: colors.mutedText,
    },
    calculateButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.success,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      flex: 1,
      justifyContent: 'center',
    },
    calculateButtonDisabled: {
      backgroundColor: colors.mutedBackground,
    },
    calculateButtonText: {
      color: colors.buttonPrimaryText,
      fontSize: 16,
      fontWeight: '600',
    },
    resultsContainer: {
      gap: 12,
    },
    resultsTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: colors.text,
      marginBottom: 8,
    },
    resultCard: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    bestResultCard: {
      borderColor: colors.primary,
      backgroundColor: colors.primaryLight,
    },
    resultHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 8,
    },
    resultName: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
      flex: 1,
      marginRight: 12,
    },
    bestResultName: {
      color: colors.primary,
      fontSize: 17,
    },
    resultScore: {
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.success,
    },
    bestResultScore: {
      fontSize: 18,
      color: colors.primary,
    },
    resultDetails: {
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 12,
      marginTop: 8,
    },
    detailsTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 8,
    },
    detailSection: {
      marginBottom: 8,
    },
    detailSectionTitle: {
      fontSize: 13,
      fontWeight: '500',
      color: colors.text,
      marginBottom: 4,
    },
    detailItem: {
      fontSize: 12,
      color: colors.mutedText,
      marginLeft: 12,
      marginBottom: 2,
    },
    noResultsContainer: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 20,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    noResultsText: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
      textAlign: 'center',
      marginBottom: 8,
    },
    noResultsSubtext: {
      fontSize: 14,
      color: colors.mutedText,
      textAlign: 'center',
    },
    resetButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.error,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      justifyContent: 'center',
      marginTop: 16,
    },
    resetButtonText: {
      color: colors.buttonPrimaryText,
      fontSize: 16,
      fontWeight: '600',
    },
    disclaimer: {
      fontSize: 12,
      color: colors.mutedText,
      opacity: 0.8,
      textAlign: 'center',
      marginTop: 24,
      paddingHorizontal: 16,
      lineHeight: 16,
    },
    // Clinical Cases Styles
    clinicalCasesContainer: {
      backgroundColor: colors.card,
      borderRadius: 12,
      marginVertical: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    clinicalCasesHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      gap: 12,
    },
    clinicalCasesTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
      flex: 1,
    },
    clinicalCasesList: {
      paddingHorizontal: 16,
      paddingBottom: 16,
    },
    clinicalCasesDescription: {
      fontSize: 14,
      color: colors.mutedText,
      marginBottom: 12,
      lineHeight: 20,
    },
    clinicalCaseItem: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 12,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    clinicalCaseHeader: {
      marginBottom: 8,
    },
    clinicalCaseName: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 4,
    },
    clinicalCaseExpected: {
      fontSize: 12,
      color: colors.success,
      fontWeight: '500',
    },
    clinicalCaseDescriptionText: { // Renamed from clinicalCaseDescription to avoid conflict
      fontSize: 13,
      color: colors.text,
      marginBottom: 6,
    },
    clinicalCaseHistory: {
      fontSize: 12,
      color: colors.mutedText,
      lineHeight: 16,
      fontStyle: 'italic',
    },
    // Anatomical Explanation Styles
    anatomicalExplanation: {
      marginTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 12,
    },
    anatomicalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 8,
    },
    anatomicalTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.primary,
      flex: 1,
    },
    anatomicalContent: {
      paddingTop: 8,
      gap: 8,
    },
    anatomicalText: {
      fontSize: 13,
      color: colors.text,
      lineHeight: 18,
      marginBottom: 8,
    },
    anatomicalSectionTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
      marginTop: 8,
      marginBottom: 4,
    },
    anatomicalStep: {
      fontSize: 12,
      color: colors.mutedText,
      lineHeight: 16,
      marginBottom: 4,
      marginLeft: 8,
    },
    anatomicalBullet: {
      fontSize: 12,
      color: colors.mutedText,
      lineHeight: 16,
      marginBottom: 2,
      marginLeft: 8,
    },
    // Dual Innervation Styles
    dualInnervationContainer: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      marginTop: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    dualInnervationHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 16,
    },
    dualInnervationTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
      flex: 1,
    },
    dualInnervationItem: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    dualInnervationHigh: {
      borderColor: colors.error,
      backgroundColor: colors.errorLight || colors.surface,
    },
    dualInnervationMedium: {
      borderColor: colors.warning,
      backgroundColor: colors.warningLight || colors.surface,
    },
    dualInnervationMuscle: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 4,
    },
    dualInnervationRelevance: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.primary,
      marginBottom: 6,
    },
    dualInnervationInterpretation: {
      fontSize: 13,
      color: colors.text,
      lineHeight: 18,
      marginBottom: 6,
    },
    dualInnervationClinical: {
      fontSize: 12,
      color: colors.mutedText,
      lineHeight: 16,
      fontStyle: 'italic',
    },
    // Feedback Styles
    feedbackContainer: {
      marginTop: 16,
      gap: 12,
    },
    feedbackMessage: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      padding: 12,
      borderRadius: 8,
      borderWidth: 1,
      gap: 8,
    },
    feedbackError: {
      backgroundColor: colors.errorLight || '#fef2f2',
      borderColor: colors.error,
    },
    feedbackWarning: {
      backgroundColor: colors.warningLight || '#fefce8',
      borderColor: colors.warning,
    },
    feedbackText: {
      fontSize: 13,
      lineHeight: 18,
      flex: 1,
    },
    feedbackTextError: {
      color: colors.error,
    },
    feedbackTextWarning: {
      color: colors.warning,
    },
    suggestionsContainer: {
      backgroundColor: colors.primaryLight || colors.surface,
      borderRadius: 8,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    suggestionsTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.primary,
      marginBottom: 8,
    },
    suggestionText: {
      fontSize: 13,
      color: colors.text,
      lineHeight: 18,
      marginBottom: 4,
    },
    // SVG Visualization Styles
    svgContainer: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
    },
    svgHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '100%',
      marginBottom: 12,
    },
    educationalLink: {
      marginRight: 8,
      backgroundColor: colors.surface,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    educationalLinkText: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: '600',
    },
    svgTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
      flex: 1,
      textAlign: 'center',
    },
    animationToggle: {
      backgroundColor: colors.surface,
      borderRadius: 6,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    animationToggleActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    animationToggleText: {
      fontSize: 12,
      color: colors.text,
      fontWeight: '500',
    },
    animationToggleTextActive: {
      color: colors.buttonPrimaryText,
    },
    svgDescription: {
      fontSize: 12,
      color: colors.mutedText,
      textAlign: 'center',
      marginTop: 8,
      fontStyle: 'italic',
      lineHeight: 16,
    },
    // New UX Styles
    controlsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
      gap: 12,
    },
    modeToggle: {
      flexDirection: 'row',
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 2,
      flex: 1,
    },
    modeButton: {
      flex: 1,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 6,
      alignItems: 'center',
    },
    modeButtonActive: {
      backgroundColor: colors.primary,
    },
    modeButtonText: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.mutedText,
    },
    modeButtonTextActive: {
      color: colors.buttonPrimaryText,
    },
    summaryToggle: {
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 6,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    summaryToggleActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    summaryToggleText: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.text,
    },
    summaryToggleTextActive: {
      color: colors.buttonPrimaryText,
    },
    quickMuscleList: {
      maxHeight: 400,
      marginTop: 8,
    },
    quickMuscleItem: {
      marginBottom: 16,
      padding: 12,
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    quickMuscleLabel: {
      fontSize: 14,
      fontWeight: '500',
      color: colors.text,
      marginBottom: 8,
    },
    regionTabs: {
      marginVertical: 8,
      maxHeight: 50,
    },
    regionTab: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      marginRight: 8,
      borderRadius: 20,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    regionTabActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    regionTabText: {
      fontSize: 13,
      fontWeight: '500',
      color: colors.text,
      textAlign: 'center',
    },
    regionTabTextActive: {
      color: colors.buttonPrimaryText,
    },
    regionMuscleList: {
      maxHeight: 350,
      marginTop: 8,
    },
    regionMuscleItem: {
      marginBottom: 16,
      padding: 12,
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    regionMuscleLabel: {
      fontSize: 14,
      fontWeight: '500',
      color: colors.text,
      marginBottom: 8,
    },
    // Flexible Navigation Styles
    stepTabs: {
      marginBottom: 20,
      maxHeight: 80,
    },
    stepTab: {
      marginRight: 12,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 12,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      minWidth: 80,
    },
    stepTabActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    stepTabComplete: {
      backgroundColor: colors.successLight || colors.surface,
      borderColor: colors.success,
    },
    stepTabContent: {
      alignItems: 'center',
    },
    stepTabNumber: {
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.text,
      marginBottom: 2,
    },
    stepTabNumberActive: {
      color: colors.buttonPrimaryText,
    },
    stepTabNumberComplete: {
      color: colors.success,
    },
    stepTabLabel: {
      fontSize: 11,
      fontWeight: '500',
      color: colors.mutedText,
      textAlign: 'center',
    },
    stepTabLabelActive: {
      color: colors.buttonPrimaryText,
    },
    actionContainer: {
      marginTop: 20,
      alignItems: 'center',
    },
    nextButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.primary,
      paddingVertical: 12,
      paddingHorizontal: 24,
      borderRadius: 8,
    },
    nextButtonText: {
      color: colors.buttonPrimaryText,
      fontSize: 16,
      fontWeight: '600',
    },
    // Confidence Metrics Styles
    confidenceSection: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 12,
      marginTop: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    confidenceBar: {
      height: 8,
      backgroundColor: colors.border,
      borderRadius: 4,
      marginVertical: 8,
      overflow: 'hidden',
    },
    confidenceLevel: {
      height: '100%',
      borderRadius: 4,
    },
    confidenceText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 8,
    },
    factorsSection: {
      marginTop: 12,
    },
    factorsTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 6,
    },
    factorItem: {
      fontSize: 12,
      color: colors.text,
      lineHeight: 16,
      marginBottom: 2,
      marginLeft: 8,
    },
    // Severity Styles
    severitySection: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 12,
      marginTop: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    severityInfo: {
      marginTop: 8,
    },
    severityGrade: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.primary,
      marginBottom: 4,
    },
    severityDescription: {
      fontSize: 13,
      color: colors.text,
      marginBottom: 6,
      lineHeight: 18,
    },
    severityPrognosis: {
      fontSize: 13,
      fontWeight: '600',
      marginBottom: 4,
    },
    severityTime: {
      fontSize: 12,
      color: colors.mutedText,
      marginBottom: 4,
    },
    severityTreatment: {
      fontSize: 12,
      color: colors.text,
      lineHeight: 16,
      fontStyle: 'italic',
    },
    // Temporal Analysis Styles
    temporalSection: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 12,
      marginTop: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    temporalPhase: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.primary,
      marginTop: 8,
      marginBottom: 4,
    },
    temporalPattern: {
      fontSize: 13,
      color: colors.text,
      marginBottom: 8,
    },
    prognosticFactors: {
      marginTop: 8,
    },
    // Clinical Context Styles
    clinicalContext: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 12,
      marginTop: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    contextAge: {
      fontSize: 13,
      color: colors.text,
      marginTop: 8,
      marginBottom: 12,
      fontWeight: '500',
    },
    contextSection: {
      marginTop: 8,
    },
  });
